#!/usr/bin/env bash
# install nginx server

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo nginx -s reload
echo Hello World! > /var/www/html/index.html
