#!/usr/bin/env bash
# install nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/defult
sudo service nginx start
