#!/usr/bin/env bash
# install nginx server and configure redirect and not found page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.html
sed -i "s/server_name _;/\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enable/default
echo "Ceci n'est pas une page" > /var/www/html/Error_404.html
sed -i "s/server_name _;/a \n\terror_page 404 \/Error_404.html;" /etc/nginx/sites-enable/default
sudo service nginx restart
