#!/usr/bin/env bash
# install nginx server and configure redirect and not found page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.html
sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enable/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/Error_404.html
sed -i '/server_name _;/a error_page 404 \/Error_404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
