#!/usr/bin/env bash
# install nginx server and configure redirect and not found page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo Hello World! | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://twitter.com/omarelgassim permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/Error_404.html
sudo sed -i '/server_name _;/a error_page 404 \/Error_404.html;' /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/a add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
sudo service nginx restart
