#!/usr/bin/env bash
# configure the load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo echo "frontend http
  bind *:80
  mode http
  default_backend web-backend
  
  backend web-backend
   balance roundrobin
    server 513072-web-01 100.27.0.202:80 check
    server 513072-web-02 54.237.42.237:80 check
  " | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart