#!/usr/bin/env bash
#print bad luck in 4 and good luck in 8 other best school
i=0
while [ $i -ne 10 ]; do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
