#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	((hour++))
	min=1
	while [ $min -le 59 ]; do
		echo $min
		((min++))

	done
done
