#!/usr/bin/env bash
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
list=$(find .| cut -d "-" -f2 | cut -d "." -f2 | cut -d "/" -f2)
for i in $list; do
	echo "$i"
done
