#!/usr/bin/env bash
server {
    listen 80;
    server_name 100.27.0.202;
    add_header X-Served-By 513072-web-01;
    location /hbnb_static/ {
        alias /data/web_static/current/;
        }                                                                                                                                                                                            
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }
    rewrite ^/redirect_me  https://twitter.com/omarelgassim permanent;
    error_page 404 /Error_404.html;
    location / {
        try_files $uri $uri/ =404;
        }                                                                                                                                                                                            
    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/airbnb-dynamic/number_odd_or_even/$1;
        }
    location /api/{
        proxy_pass http://127.0.0.1:5002/api/;
    }
}